project:
   title: "frm-survey"
   type: website
   output-dir: docs
   execute-dir: project
   render:
    - cruises/plans/frm-pot_cruiseplan_20220829.qmd

author: "Mike O'Brien (UMCES)"
format:
    html:
      self-contained: true
fontsize: 16px
editor: visual

website:
  title: "mysite"
  navbar:
    background: primary
    left:
      - href: cruises/plans/frm-pot_cruiseplan_20220829.qmd
        text: Home
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
