name: fishweather_scraping

# https://crontab.guru/
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0,12 * * *'


jobs: 
  scrape_it:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      
    steps:
    - name: Check out GH repository
      uses: actions/checkout@v3
      
    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        use-public-rspm: true

    - name: Install packages
      uses: r-lib/actions/setup-r-dependencies@v2
      with:
        packages: |
          any::rvest
          any::httr
          any::jsonlite
          any::qs
        
    - name: Scrape with R script
      run: Rscript "fishweather_scrape.R"
      
 # Add new files in data folder, commit along with other modified files, push
    - name: Commit files
      run: |
        git config --local user.name actions-user
        git config --local user.email "actions@github.com"
        git add .
        git commit -am "GH ACTION scraped fishweather on $(date)"
        git push origin main
